# Introduction

In [2]:
import numpy as np

# Arrays

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [14]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [15]:
# Get type
print([a.dtype, b.dtype])

[dtype('int64'), dtype('float64')]


In [ ]:
# Get size in bytes
print([a.itemsize , b.itemsize])

[8, 8]
